# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
#   desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

#   desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to the firebase"
  lane :distribute_to_firebase do |options|
          gradle(
              task: 'assemble',
#              flavor: options[:flavor],
              build_type: options[:buildType]
          )
          firebase_app_distribution(
              app: "1:491808774920:android:cce64719ad7b129b412abd",
              testers: "huuvietuet@gmail.com",
              release_notes: "Release message!"
          )
  end

  desc "Deploy a new version to the deploygate"
  lane :distribute_to_deploygate do |options|
      gradle(
          task: 'assemble',
#            flavor: options[:flavor],
          build_type: options[:buildType]
      )
      # build_android_app is a built-in fastlane action.
      deploygate(
        api_token: options[:deployGateToken],
        user: options[:userName],
        apk: "./app/build/outputs/apk/#{options[:buildType]}/app-#{options[:buildType]}.apk",
        message: "release",
        distribution_key: "6b3fdb6256e08a251d56a14082d6cf6088abe1ae"
      )
  end

end
